# Generated by Django 5.0.7 on 2024-08-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woomen', '0002_rename_time_creat_woomen_time_create'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='woomen',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='woomen',
            name='slug',
            field=models.SlugField(blank=True, default=0, max_length=255),
        ),
        migrations.AddIndex(
            model_name='woomen',
            index=models.Index(fields=['-time_create'], name='woomen_woom_time_cr_038eb4_idx'),
        ),
    ]
