# Generated by Django 5.0.7 on 2024-08-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woomen', '0003_alter_woomen_options_woomen_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woomen',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
