# Generated by Django 5.0.7 on 2024-08-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woomen', '0004_alter_woomen_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woomen',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0),
        ),
    ]
